kind: WorkflowTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mirror-and-customize
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: architectures
      - name: cleanup
        enum:
          - "false"
          - "true"
      - default: ""
        name: os-image
        value: ""
      - name: os-name
      - default: ""
        name: os-buildconfig
        value: ""
      - default: quay.io/<org>/okd-release-argo:4.13.0-0.okd-2021-12-11-200126
        name: release-image-location
      - default: quay.io/<org>/okd-release-argo
        name: release-mirror-location
      - default: registry-robot-token
        name: registry-credentials-secret-ref
      - name: initial-payload
      - name: buildconfigs-batched-list
        default: |
          [
            [ { "buildConfig": "my-build-config-1", "overrideRepoUrl": "....", "overrideBranch": "my-branch" } ],
            [ { "buildConfig": "my-build-config-on-batch-2", "overrideRepoUrl": "....", "overrideBranch": "my-branch" } ]
          ]
      - name: delete-istags
        default: |
          []
  templates:
    - name: entrypoint
      steps:
        - - name: cleanup
            when: "{{workflow.parameters.cleanup}}==true"
            templateRef:
              name: wftpl-cleanup
              template: cleanup
        - - name: mirror-initial-release
            when: '''{{workflow.parameters.initial-payload}}''!='''''
            templateRef:
              name: wftpl-release
              template: mirror-initial-release
            arguments:
              parameters:
                - name: registry-credentials-secret-ref
                  value: "{{workflow.parameters.registry-credentials-secret-ref}}"
                - name: release-image-location
                  value: "{{workflow.parameters.initial-payload}}"
        - - name: delete-istags
            when: '''{{workflow.parameters.initial-payload}}''!='''''
            templateRef:
              name: wftpl-imagestreamtag
              template: delete-imagestreamtag
            arguments:
              parameters:
                - name: name
                  value: "{{item}}"
            withParam: "{{workflow.parameters.delete-istags}}"
        - - name: recreate-os-imagestreamtags
            when: '''{{workflow.parameters.os-image}}''!='''''
            templateRef:
              name: wftpl-imagestreamtag
              template: replace-imagestreamtag
            arguments:
              parameters:
                - name: name
                  value: "{{item}}"
                - name: image
                  value: "{{workflow.parameters.os-image}}"
            withItems:
              - "{{workflow.parameters.os-name}}"
              - machine-os-content
        - - name: initial
            template: batches
            arguments:
              parameters:
                - name: buildconfigs-batched-list
                  value: |
                    [
                      [
                        { "buildConfig": "builder", "overrideRepoUrl": "", "overrideBranch": "" },
                        { "buildConfig": "forked-dockerfiles", "overrideRepoUrl": "", "overrideBranch": "" },
                        { "buildConfig": "base", "overrideRepoUrl": "", "overrideBranch": "" } 
                    
                      ],
                      [ { "buildConfig": "cli", "overrideRepoUrl": "", "overrideBranch": "" } ]
                    ]
        - - name: batches
            template: batches
            arguments:
              parameters:
                - name: buildconfigs-batched-list
                  value: "{{workflow.parameters.buildconfigs-batched-list}}"
        - - name: build-os
            template: build-os
            when: '''{{workflow.parameters.os-buildconfig}}''!='''''
        - - name: package-release
            templateRef:
              name: wftpl-release
              template: package-release
            arguments:
              parameters:
                - name: registry-credentials-secret-ref
                  value: "{{workflow.parameters.registry-credentials-secret-ref}}"
                - name: release-image-location
                  value: '{{workflow.parameters.release-image-location}}'
                - name: release-mirror-location
                  value: '{{workflow.parameters.release-mirror-location}}'
    - name: batches
      parallelism: 1
      failFast: true
      inputs:
        parameters:
          - name: buildconfigs-batched-list
      steps:
        - - template: single-batch
            withParam: "{{inputs.parameters.buildconfigs-batched-list}}"
            arguments:
              parameters:
                - name: buildconfigs-list
                  value: "{{item}}"
    - name: single-batch
      failFast: true
      parallelism: 8
      inputs:
        parameters:
          - name: buildconfigs-list
      steps:
        - - name: single-batch
            templateRef:
              name: wftpl-build-memoize
              template: multiarch-build
            arguments:
              parameters:
                - name: build-config-name
                  value: "{{item.buildConfig}}"
                - name: repo-url
                  value: "{{item.overrideRepoUrl}}"
                - name: branch
                  value: "{{item.overrideBranch}}"
                - name: architectures
                  value: "{{workflow.parameters.architectures}}"
            withParam: "{{inputs.parameters.buildconfigs-list}}"
    - name: build-os
      steps:
        - - arguments:
              parameters:
                - name: build-config-name
                  value: '{{workflow.parameters.os-buildconfig}}'
                - name: architectures
                  value: "{{workflow.parameters.architectures}}"
            name: build-os
            templateRef:
              name: wftpl-build-memoize
              template: multiarch-build
        - - inline:
              resource:
                action: apply
                manifest: |
                  apiVersion: image.openshift.io/v1
                  kind: ImageStreamTag
                  metadata:
                    name: release:machine-os-content
                  tag:
                    from:
                      kind: ImageStreamTag
                      name: "release:{{workflow.parameters.os-name}}"
                    importPolicy:
                      importMode: PreserveOriginal
            name: set-machine-os-content
