apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fedora-coreos
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/okd-machine-os'
      ref: master
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'tools:fedora-coreos'
        as:
          - 'quay.io/coreos-assembler/fcos:next-devel'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: None
  output:
    to:
      kind: ImageStreamTag
      name: 'release:fedora-coreos'
